DROP TABLE USER_RATEDMOVIES_TIMESTAMPS;
DROP TABLE USER_RATEDMOVIES;
DROP TABLE USER_TAGGEDMOVIES_TIMESTAMPS;
DROP TABLE USER_TAGGEDMOVIES;
DROP TABLE MOVIE_TAGS;
DROP TABLE TAGS;
DROP INDEX COUNTRY_INDEX;
DROP TABLE MOVIE_LOCATIONS;
DROP INDEX COUNTRY_INDEX;
DROP TABLE MOVIE_COUNTRIES;
DROP TABLE MOVIE_ACTORS;
DROP TABLE MOVIE_DIRECTORS;
DROP INDEX GENRE_INDEX;
DROP TABLE MOVIE_GENRES;
DROP INDEX GENRE_MID_INDEX;
DROP INDEX MOVIE_YEAR;
DROP INDEX MOVIE_INDEX;
DROP TABLE MOVIES;


